version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/codeDeploy/
permissions:
  - object: /home/ubuntu/codeDeploy
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/remove.sh
      timeout: 300
      runas: root
      mode: 777
  AfterInstall:
    - location: scripts/dependencies.sh
      timeout: 300
      runas: ubuntu
